AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  weather-serverless-api
  
  Sample SAM Template for weather-serverless-api

Globals:
  Function:
    Timeout: 5

Resources:
  WeatherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: weather-api/
      Handler: weather-api
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /weather/{country}
            Method: GET
      Environment:
        Variables:
          HOST: api.openweathermap.org
          ENDPOINT: data/2.5/weather
          TOKEN: /weather/dev/token