AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  weather-serverless-api
  
  Sample SAM Template for weather-serverless-api

Globals:
  Function:
    Timeout: 5

Resources:
  WeatherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: weather-api/
      Handler: weather-api
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /weather/{country}
            Method: GET
      Environment:
        Variables:
          HOST: api.openweathermap.org
          ENDPOINT: data/2.5/weather
          TOKEN: /weather/dev/token

Outputs:
  WeatherAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/weather/{country}"
  WeatherFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt WeatherFunction.Arn
  WeatherFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt WeatherFunctionRole.Arn
